spring:
  application:
    name: AIRecognize

  datasource:
    url: jdbc:mysql://localhost:<port>/<db>
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: <un>
    password: <pw>

  jpa:
    hibernate:
      ddl-auto: create

    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

